/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'causeOfDeath' : IDL.Text,
  'category' : IDL.Text,
  'potentialScore' : IDL.Float64,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'causeOfDeath' : IDL.Text,
    'category' : IDL.Text,
    'potentialScore' : IDL.Float64,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };